### PR TITLE
Write features tests for DeleteCourse and Reservation Pages

### PR DESCRIPTION
**Pull request by tobuya**
# Writing tests for pages
I added the following changes in this branch:
- Added tests for the following pages:
  - Delete Course Page
  - Reservation Page

*Run `npm test` to test the frontend components*

[Feature Tests](https://github.com/users/IndieCoderMM/projects/4/views/1?filterQuery=assignee%3A&pane=issue&itemId=28527344)

### CODE REVIEW

**Review by tanveerisonline — CHANGES_REQUESTED** [review]
### STATUS: CHANGES REQUIRED ♻️♻️
**_Hi @tobuya_** 
Good job working on the project so far!
**To highlight 👍🏼 **
✔️ Unit tests are added for Delete Course.
✔️ Unit tests are added for Reservation Pages.
✔️ Tests are placed in spec folder
✔️ Tests use describe block

**However, there are some issues that you need to work on to go to the next project but you are almost there!**
change
### Required Changes ♻️

**When I test this code, I get this error. Kindly fix it**

test_failure

**Comment by tobuya** [comment]
Hi @tanveerisonline, all the tests are passing on my side. Would you please provide more information on the snapshot error you are facing?
VirtualBox_Xubuntu_29_05_2023_19_19_45

**Comment by tanveerisonline** [comment]
### Hi @tobuya 
The attachments are the details of the error kindly check them and fix them thanks.

**Review by tanveerisonline — APPROVED** [review]

**Review by tanveerisonline — APPROVED** [review]
### Hi @tobuya 
**your work is done and now its time to merge it** 
**happy coding 😄 😄**

**Pull request merged**
